#!/bin/env bash

: "${WORKSPACE_FOLDER:="${GITPOD_REPO_ROOT}"}"

if [ -z "$WORKSPACE_FOLDER" ] ; then
    return
fi

export WORKSPACE_FOLDER

alias wp="/usr/local/share/library-scripts/compose-exec wordpress wp"
alias php="/usr/local/share/library-scripts/compose-exec wordpress php"
alias composer="/usr/local/share/library-scripts/compose-exec wordpress composer"
alias mysqldump="/usr/local/share/library-scripts/compose-exec db mysqldump"
alias mysql="/usr/local/share/library-scripts/compose-exec db mysql"
